version: "3.6"

services:
  ionic:
    image: guideo/ionic-frontend:1.0.39
    networks:
      - frontend
    depends_on:
      - guideo

  mongo:
    image: mongo
    networks:
      - backend
    volumes:
      - db-data:/data/db
    ports:
      - 27017:27017

  guideo:
    image: guideo/guideo:1.3.4
    environment: 
      DB_URL: mongodb://10.2.0.2:27017
      DB_NAME: guideo
    networks:
      - backend
    volumes: 
      - "./public:/app/public"
    depends_on: 
      - mongo

volumes: 
  db-data:

networks:
  backend:
    name: backend
    driver: bridge
    ipam:
      config:
        - subnet: 10.2.0.0/16
  frontend:
    name: frontend
    driver: bridge
    ipam:
      config:
        - subnet: 10.3.0.0/16
