version: '3.6'

services: 
    guideo:
        # build: 
        #     context: .
        #     dockerfile: server.Dockerfile
        #     args: 
        #         - PORT=3030
        # image: guideo
        image: guideo/guideo:0.6.0
#        container_name: guideo
        environment: 
            DB_URL: mongodb://192.168.99.100:27017
            DB_NAME: guideo
        ports: 
            - 3030:3030
        volumes: 
        #    - server-data:/app/public
            - "./public:/app/public"
        depends_on: 
            - mongo

    ionic-frontend:
        image: guideo/ionic-frontend:1.0.1
        ports: 
            - 80:80
        depends_on: 
            - guideo

    mongo:
        image: mongo
        ports: 
            - "27017:27017"
        volumes:
            - db-data:/data/db

volumes: 
    # server-data:
    db-data:
