version: '3.6'

services: 
    guideo:
        # build: 
        #     context: .
        #     dockerfile: server.Dockerfile
        #     args: 
        #         - PORT=3030
        #image: guideo
        image: guideo/guideo:0.2.0
#       container_name: guideo
        environment: 
            DB_URL: mongodb://172.17.0.1:27017
            DB_NAME: guideo
        ports: 
            - 8443:3030
        volumes:
            - server-data:/app/public
        depends_on: 
            - mongo
    mongo:
        image: mongo
        ports: 
            - "27017:27017"
volumes:
    server_data:
