loglevel = "INFO"

defaultEntryPoints = ["http", "https"]

[web]
    address = ":8080"

# Force HTTPS
[entryPoints]
    [entryPoints.http]
    assress = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"
    [entryPoints.https]
    address = ":443"
        [entryPoints.https.tls]

[docker]
    domain = "vm62.htl-leonding.ac.at"
    watch = true
    exposedbydefault = false

# Let's encrypt configuration
[acme]
    email="luke.wirth31@gmail.com"
    storage="/etc/traefik/acme/acme.json"
    entryPoint="https"
    acmeLogging=true
    OnHostRule=true
    [acme.httpChallenge]
        entryPoint = "http"